# Generated by Django 4.1.2 on 2022-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=16, verbose_name='Cерия')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата окончания действия')),
                ('use_date', models.DateTimeField(verbose_name='Дата использования')),
                ('balance', models.FloatField(verbose_name='Баланс')),
                ('status', models.CharField(choices=[('N', 'NOT_ACTIVATED'), ('A', 'ACTIVATED'), ('O', 'OVERDUE')], max_length=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бонусная карта',
                'verbose_name_plural': 'Бонусные карты',
            },
        ),
    ]
