# Generated by Django 4.1.2 on 2022-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(max_length=4, verbose_name='Cерия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('N', 'NOT_ACTIVATED'), ('A', 'ACTIVATED'), ('E', 'EXPIRED')], default='N', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='card',
            name='use_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
    ]
