# Generated by Django 4.1.2 on 2022-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_balance_alter_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Номер'),
        ),
    ]
