# Generated by Django 4.1.2 on 2022-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата выпуска'),
        ),
    ]
