# Generated by Django 4.1.2 on 2022-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска'),
        ),
    ]
